In [2]:
a = [10, 11, 12, 13, 14, 15]

In [3]:
import numpy as np

In [4]:
n_a = np.array(a)

In [5]:
n_a

array([10, 11, 12, 13, 14, 15])

In [6]:
n_a[0]

10

In [7]:
n_a[1]

11

In [8]:
last_index = len(n_a) - 1
n_a[last_index]

15

In [9]:
n_a[-1]

15

【演習】最後から２番目の要素を表示するには？

In [30]:
n_a[-2]

14

In [10]:
n_a[0:3]

array([10, 11, 12])

In [11]:
n_a[:3]

array([10, 11, 12])

In [12]:
n_a[3:6]

array([13, 14, 15])

In [13]:
n_a[3:]

array([13, 14, 15])

In [14]:
n_a[2:4]

array([12, 13])

【演習】最初と最後以外の要素を表示させるには？

In [31]:
n_a[1:-1]

array([11, 12, 13, 14])

In [15]:
n_a[::2]

array([10, 12, 14])

In [16]:
n_a[1::2]

array([11, 13, 15])

In [17]:
n_b = np.array([100, 101, 102, 103, 104, 105])

In [18]:
n_c = np.concatenate([n_a, n_b])

In [19]:
n_c

array([ 10,  11,  12,  13,  14,  15, 100, 101, 102, 103, 104, 105])

In [20]:
np.sum(n_c)

690

In [21]:
np.max(n_c)

105

In [22]:
np.min(n_c)

10

【演習】平均値を計算するには？

In [32]:
np.mean(n_c)

57.5

In [23]:
n_random = np.random.random(10)

In [24]:
n_random

array([0.38714689, 0.12493765, 0.66667522, 0.26476645, 0.97565287,
       0.62185769, 0.98127697, 0.1313084 , 0.37230031, 0.34534234])

In [25]:
np.max(n_random)

0.9812769747504453

In [26]:
np.min(n_random)

0.12493765055524797

In [27]:
np.sort(n_random)

array([0.12493765, 0.1313084 , 0.26476645, 0.34534234, 0.37230031,
       0.38714689, 0.62185769, 0.66667522, 0.97565287, 0.98127697])

In [28]:
np.argsort(n_random)

array([1, 7, 3, 9, 8, 0, 5, 2, 4, 6])

【演習】降順のソートをするには？

In [29]:
np.sort(n_random)[::-1]

array([0.98127697, 0.97565287, 0.66667522, 0.62185769, 0.38714689,
       0.37230031, 0.34534234, 0.26476645, 0.1313084 , 0.12493765])