配列の作成

In [1]:
a = [10, 11, 12, 13, 14, 15]

In [2]:
import numpy as np

In [3]:
n_a = np.array(a)

In [4]:
n_a

array([10, 11, 12, 13, 14, 15])

配列の要素へのアクセス（インデックスによるアクセス）

In [5]:
n_a[0]

10

In [6]:
n_a[1]

11

In [7]:
last_index = len(n_a) - 1
n_a[last_index]

15

In [8]:
n_a[-1]

15

【演習】最後から２番目の要素を表示するには？

部分配列（スライス）

In [9]:
n_a[0:3]

array([10, 11, 12])

In [10]:
n_a[:3]

array([10, 11, 12])

In [11]:
n_a[3:6]

array([13, 14, 15])

In [12]:
n_a[3:]

array([13, 14, 15])

In [13]:
n_a[2:4]

array([12, 13])

【演習】最初と最後以外の要素を表示させるには？

In [14]:
n_a[::2]

array([10, 12, 14])

In [15]:
n_a[1::2]

array([11, 13, 15])

配列の連結

In [16]:
n_b = np.array([100, 101, 102, 103, 104, 105])

In [17]:
n_c = np.concatenate([n_a, n_b])

In [18]:
n_c

array([ 10,  11,  12,  13,  14,  15, 100, 101, 102, 103, 104, 105])

配列の計算

合計、最大、最小

In [19]:
np.sum(n_c)

690

In [20]:
np.max(n_c)

105

In [21]:
np.min(n_c)

10

【演習】平均値を計算するには？

配列のソート

In [22]:
n_random = np.random.random(10)

In [23]:
n_random

array([0.81491751, 0.56761835, 0.31188333, 0.78329443, 0.2675528 ,
       0.85589734, 0.91496817, 0.53151113, 0.23812665, 0.88668392])

In [24]:
np.max(n_random)

0.914968172246989

In [25]:
np.min(n_random)

0.23812664857563137

In [26]:
np.sort(n_random)

array([0.23812665, 0.2675528 , 0.31188333, 0.53151113, 0.56761835,
       0.78329443, 0.81491751, 0.85589734, 0.88668392, 0.91496817])

In [27]:
np.argsort(n_random)

array([8, 4, 2, 7, 1, 3, 0, 5, 9, 6], dtype=int64)

【演習】降順のソートをするには？