In [26]:
a = [10, 11, 12, 13, 14, 15]

In [27]:
import numpy as np

In [28]:
n_a = np.array(a)

In [29]:
n_a

array([10, 11, 12, 13, 14, 15])

In [30]:
n_a[0]

10

In [31]:
n_a[1]

11

In [32]:
last_index = len(n_a) - 1
n_a[last_index]

15

In [33]:
n_a[0:3]

array([10, 11, 12])

In [34]:
n_a[:3]

array([10, 11, 12])

In [35]:
n_a[3:6]

array([13, 14, 15])

In [36]:
n_a[3:]

array([13, 14, 15])

In [37]:
n_a[2:4]

array([12, 13])

In [38]:
n_a[::2]

array([10, 12, 14])

In [39]:
n_a[1::2]

array([11, 13, 15])

In [40]:
n_b = np.array([100, 101, 102, 103, 104, 105])

In [42]:
n_c = np.concatenate([n_a, n_b])

In [43]:
n_c

array([ 10,  11,  12,  13,  14,  15, 100, 101, 102, 103, 104, 105])

In [46]:
np.sum(n_c)

690

In [47]:
np.max(n_c)

105

In [48]:
np.min(n_c)

10

In [50]:
n_random = np.random.random(10)

In [51]:
n_random

array([0.08914546, 0.42793385, 0.27591313, 0.52348563, 0.89570579,
       0.63140215, 0.8251887 , 0.48485422, 0.56194013, 0.11139841])

In [52]:
np.max(n_random)

0.8957057908155619

In [54]:
np.min(n_random)

0.08914545747547953

In [55]:
np.sort(n_random)

array([0.08914546, 0.11139841, 0.27591313, 0.42793385, 0.48485422,
       0.52348563, 0.56194013, 0.63140215, 0.8251887 , 0.89570579])

In [56]:
np.argsort(n_random)

array([0, 9, 2, 1, 7, 3, 8, 5, 6, 4])

In [57]:
np.sort(n_random)[::-1]

array([0.89570579, 0.8251887 , 0.63140215, 0.56194013, 0.52348563,
       0.48485422, 0.42793385, 0.27591313, 0.11139841, 0.08914546])